[package]
name = "splash_protocol"
version = "0.0.1"
edition = "2024.beta"
license = "Apache-2.0"
authors = ["Splash Finance"]

[dependencies]
deepbook = { git = "https://github.com/MystenLabs/deepbookv3.git", subdir = "packages/deepbook", rev = "daa5a9514908968f11be1d0388f673e0ee1a5059" }
openzeppelin_math = { git = "https://github.com/OpenZeppelin/contracts-sui.git", subdir = "math/core", rev = "a9703fe834a56990ccbcee3a1cf0802e7cd3b8d9" }

[addresses]
splash_protocol = "0x0"
